spring.application.name=deepfake-backend
# Le port de ton API Spring Boot
server.port=8080

# Taille maximale des fichiers audio acceptés (très important pour les .flac ou .wav)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/deepfake_pfa?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true